services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - trascendence-network


  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./back/src:/app/src
      - /app/node_modules
    env_file:
      - ./back/.env 
    environment:
      - NODE_ENV=development
      - DB_HOST=mariadb
    restart: on-failure
    networks:
      - trascendence-network
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    
    image: mariadb:latest
    ports:
      - "3306:3306"
    container_name: mariadb
    restart: always
    environment:
      # Tienen que coincidir con tu .env
      - MYSQL_DATABASE=transcendence      # Igual a DB_NAME
      - MYSQL_USER=transcendence42        # Igual a DB_USER
      - MYSQL_PASSWORD=transcendence42    # Igual a DB_PASSWORD
      - MYSQL_ROOT_PASSWORD=root_secret   # Contrase√±a para el usuario root (opcional pero recomendada)
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - trascendence-network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  adminer:
    image: adminer
    ports:
      - 8081:8080
    container_name: adminer
    networks:
      - trascendence-network

volumes:
    mariadb_data:

networks:
  trascendence-network:
    driver: bridge