services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - trascendence-network


  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./back/src:/app/src
      - /app/node_modules
    env_file:
      - ./back/.env # Carga las variables desde back/.env
    environment:
      - NODE_ENV=development
    restart: on-failure
    networks:
      - trascendence-network

  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    container_name: mariadb
    restart: always
    environment:
      # Tienen que coincidir con tu .env
      - MYSQL_DATABASE=transcendence      # Igual a DB_NAME
      - MYSQL_USER=transcendence42        # Igual a DB_USER
      - MYSQL_PASSWORD=transcendence42    # Igual a DB_PASSWORD
      - MYSQL_ROOT_PASSWORD=root_secret   # Contrase√±a para el usuario root (opcional pero recomendada)
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - trascendence-network

volumes:
    mariadb_data:

networks:
  trascendence-network:
    driver: bridge
